"use client";
import "./globals.css";

import { createContext, useEffect, useState } from "react";
import { Header } from "../components/header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const TokenContext = createContext();

export default function RootLayout({ children }) {
  const [token, setToken] = useState("token");
  useEffect(() => {
    if (typeof window !== "undefined") {
      const token = localStorage.getItem("token") || "";
      setToken(token);
    }
  });
  // let value = "";
  // if (typeof window !== "undefined") {
  //   value = localStorage.getItem("token") || "";
  // }

  // console.log(token);
  return (
    <html>
      <body>
        <TokenContext.Provider value={{ token, setToken }}>
          <Header />
          {children}
        </TokenContext.Provider>
      </body>
    </html>
  );
}
